#!/bin/bash
if [ "$1" != "" ]; then
	echo "- $1 ==>	$2" >> README.md
	git add . && git commit -m "0x06. C - More pointers, arrays and strings" && git push
	
    else
	        echo "Positional parameter 1 is empty"
fi
