#!/bin/bash
if [ "$1" != "" ]; then
	echo "- $1 ==>	$2" >> README.md
	git add . && git commit -m "0x13. C - More singly linked lists" && git push
	
    else
	        echo "Positional parameter 1 is empty"
fi
